create table public.subjects (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

insert into public.subjects (name)
values
  ('מתמטיקה'),
  ('אנגלית'),
  ('עברית'),
  ('קריאה וכתיבה'),
  ('מדעים'),
  ('הכנת שיעורי בית'),
  ('מיומנויות למידה'),
  ('מחשבים וטכנולוגיה'),
  ('כדורגל'),
  ('ספורט וכושר'),
  ('מוזיקה'),
  ('אמנות ויצירה'),
  ('כישורים חברתיים'),
  ('חיזוק ביטחון עצמי'),
  ('אחר');

create table public.mentor_subjects (
  user_id uuid not null references auth.users(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  age_groups text[] not null,
  custom_subject text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  primary key (user_id, subject_id),

  constraint mentor_subjects_age_groups_not_empty
    check (cardinality(age_groups) > 0),

  constraint mentor_subjects_age_groups_allowed
    check (
      age_groups <@ array[
        'א׳–ב׳',
        'ג׳–ד׳',
        'ה׳–ו׳',
        'חטיבת ביניים',
        'תיכון'
      ]::text[]
    ),

  constraint mentor_subjects_custom_subject_not_blank
    check (
      custom_subject is null
      or char_length(trim(custom_subject)) > 0
    )
);

alter table public.subjects enable row level security;
alter table public.mentor_subjects enable row level security;

revoke all on table public.subjects from anon;
revoke all on table public.subjects from authenticated;
grant select on table public.subjects to authenticated;

revoke all on table public.mentor_subjects from anon;
revoke all on table public.mentor_subjects from authenticated;
grant select, insert, update, delete
on table public.mentor_subjects
to authenticated;

create policy "Authenticated users can read subjects"
on public.subjects
for select
to authenticated
using (true);

create policy "Mentors can read their own subject choices"
on public.mentor_subjects
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Mentors can insert their own subject choices"
on public.mentor_subjects
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Mentors can update their own subject choices"
on public.mentor_subjects
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Mentors can delete their own subject choices"
on public.mentor_subjects
for delete
to authenticated
using ((select auth.uid()) = user_id);
