export const CITY_LOOKUP = new Set([
  "ירושלים",
  "תל אביב-יפו",
  "חיפה",
  "באר שבע",
  "ראשון לציון",
  "פתח תקווה",
  "אשדוד",
  "נתניה",
  "רמת גן",
  "רחובות",
  "בני ברק",
  "חולון",
  "אשקלון",
  "הרצליה",
  "רעננה",
  "כפר סבא",
  "הוד השרון",
  "נצרת",
  "בית שמש",
  "לוד",
  "בת ים",
  "קריית גת",
  "רמלה",
  "מודיעין-מכבים-רעות",
  "אילת",
  "צפת",
  "עפולה",
  "שדרות",
  "נוף הגליל",
  "יבנה",
  "כוכב השחר",
  "מעלה אדומים",
  "ערד",
  "מגדל העמק",
  "אלעד",
  "גבעתיים",
  "נס ציונה",
  "אור יהודה",
  "טבריה",
  "אבן יהודה",
  "כפר יונה",
  "רמת השרון",
  "יהוד-מונוסון",
  "שוהם",
  "גבעת שמואל",
  "כפר סבא",
  "קריית אונו",
  "ראש העין",
  "שפיים",
  "מזכרת בתיה",
  "גדרה",
  "נשר",
  "רמת ישי",
  "לכיש",
  "אופקים",
  "מנשה",
  "סח'נין",
  "טייבה",
  "טירת כרמל",
  "ביתר עילית",
  "בנימינה-גבעת עדה",
  "עומר",
  "עכו",
  "חדרה",
  "מועצה אזורית חבל אילות",
  "מועצה אזורית מגידו",
  "מועצה אזורית עמק חפר",
  "מועצה אזורית גדרות",
]);

export function normalizeCityKey(value: string) {
  return value.trim().replace(/\s+/g, " ").replace(/"/g, "").replace(/\u00a0/g, " ").trim();
}

export function findCityMatches(input: string) {
  const query = normalizeCityKey(input).toLowerCase();
  if (!query) return [];
  const matches = [...CITY_LOOKUP].filter((city) => city.toLowerCase().includes(query));
  return matches.slice(0, 12);
}

export const OFFICIAL_ISRAELI_CITIES = [...CITY_LOOKUP].sort((a, b) => a.localeCompare(b, "he", { sensitivity: "base" }));
