"use client";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "../../../../lib/supabase";
import { ChoicePills, Field, FormMessage, LoadingPage, MentorPageShell, SavePanel, inputClassName, toggleValue } from "../_components/MentorPageShell";
const AGES = ["א׳–ב׳", "ג׳–ד׳", "ה׳–ו׳", "חטיבת ביניים", "תיכון"]; const MODES = ["פרונטלי", "אונליין"]; const FORMATS = ["מפגש אישי", "קבוצה קטנה"];
export default function PreferencesPage() {
  const router = useRouter(); const [userId, setUserId] = useState(""); const [ages, setAges] = useState<string[]>([]); const [gender, setGender] = useState("אין העדפה"); const [distance, setDistance] = useState("10"); const [modes, setModes] = useState<string[]>([]); const [formats, setFormats] = useState<string[]>([]); const [meetings, setMeetings] = useState("1"); const [duration, setDuration] = useState("60"); const [specialNeeds, setSpecialNeeds] = useState(false); const [info, setInfo] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<FormMessage>(null);
  useEffect(() => { async function load() { const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return router.replace("/login"); setUserId(auth.user.id); const { data, error } = await supabase.from("mentor_preferences").select("*").eq("user_id", auth.user.id).maybeSingle(); if (error) { console.error(error); setMessage({ type: "error", text: `שגיאה בטעינה: ${error.message}` }); } if (data) { setAges(data.preferred_age_groups ?? []); setGender(data.preferred_gender); setDistance(String(data.max_travel_distance_km)); setModes(data.meeting_modes ?? []); setFormats(data.session_formats ?? []); setMeetings(String(data.preferred_meetings_per_week)); setDuration(String(data.preferred_session_duration_minutes)); setSpecialNeeds(data.willing_special_needs); setInfo(data.additional_matching_info ?? ""); } setLoading(false); } load(); }, [router]);
  async function save(e: FormEvent) { e.preventDefault(); if (!ages.length || !modes.length || !formats.length) return setMessage({ type: "error", text: "יש לבחור שכבת גיל, אופן מפגש ומבנה מפגש." }); setSaving(true); setMessage(null); const { error } = await supabase.from("mentor_preferences").upsert({ user_id: userId, preferred_age_groups: ages, preferred_gender: gender, max_travel_distance_km: Number(distance), meeting_modes: modes, session_formats: formats, preferred_meetings_per_week: Number(meetings), preferred_session_duration_minutes: Number(duration), willing_special_needs: specialNeeds, additional_matching_info: info.trim() || null, updated_at: new Date().toISOString() }); if (error) console.error(error); setMessage(error ? { type: "error", text: `שגיאה בשמירה: ${error.message}` } : { type: "success", text: "העדפות ההתאמה נשמרו בהצלחה." }); setSaving(false); }
  if (loading) return <LoadingPage text="טוען העדפות..." />;
  return <MentorPageShell title="העדפות התאמה" description="ההעדפות הן כלי עזר להתאמה ואינן תנאי אוטומטי לפסילה."><form onSubmit={save} className="space-y-6 rounded-3xl border border-blue-100 bg-white p-8 shadow-xl">
    <div><h2 className="mb-3 font-bold">שכבות גיל מועדפות</h2><ChoicePills options={AGES} selected={ages} onToggle={(v) => setAges(toggleValue(ages, v))} /></div>
    <div className="grid gap-5 md:grid-cols-2"><Field label="מגדר מועדף" htmlFor="gender"><select id="gender" value={gender} onChange={(e) => setGender(e.target.value)} className={inputClassName}><option>אין העדפה</option><option>בן</option><option>בת</option></select></Field><Field label="מרחק נסיעה מרבי (ק״מ)" htmlFor="distance"><input id="distance" type="number" min="0" required value={distance} onChange={(e) => setDistance(e.target.value)} className={inputClassName} /></Field></div>
    <div><h2 className="mb-3 font-bold">אופן המפגש</h2><ChoicePills options={MODES} selected={modes} onToggle={(v) => setModes(toggleValue(modes, v))} /></div>
    <div><h2 className="mb-3 font-bold">מבנה המפגש</h2><ChoicePills options={FORMATS} selected={formats} onToggle={(v) => setFormats(toggleValue(formats, v))} /></div>
    <div className="grid gap-5 md:grid-cols-2"><Field label="מפגשים רצויים בשבוע" htmlFor="meetings"><input id="meetings" type="number" min="1" required value={meetings} onChange={(e) => setMeetings(e.target.value)} className={inputClassName} /></Field><Field label="משך מפגש רצוי (דקות)" htmlFor="duration"><input id="duration" type="number" min="15" step="15" required value={duration} onChange={(e) => setDuration(e.target.value)} className={inputClassName} /></Field></div>
    <label className="flex items-center gap-3 rounded-xl bg-slate-50 p-4 font-bold"><input type="checkbox" checked={specialNeeds} onChange={(e) => setSpecialNeeds(e.target.checked)} className="h-5 w-5 accent-blue-600" />מוכן לחונכות עם ילד עם צרכים מיוחדים</label>
    <Field label="מידע נוסף לצורך ההתאמה" htmlFor="info"><textarea id="info" rows={4} value={info} onChange={(e) => setInfo(e.target.value)} className={inputClassName} /></Field>
    <SavePanel saving={saving} message={message} label="שמירת העדפות" />
  </form></MentorPageShell>;
}
