"use client";

import { useEffect, useMemo, useState } from "react";
import { MentorPageShell } from "../_components/MentorPageShell";
import { supabase } from "@/lib/supabase";

const DAYS = ["ראשון", "שני", "שלישי", "רביעי", "חמישי", "שישי", "שבת"];
const DURATIONS = [30, 45, 60, 75, 90];
type Meeting = { id: string; requested_start_at: string; confirmed_start_at?: string | null; child_first_name: string; subject: string; status: string };
type WindowRow = { id: string; weekday: number; start_time: string; end_time: string; meeting_mode: string; location: string | null; supported_durations: number[]; is_active: boolean; subject_ids: number[]; effective_start_date: string | null; effective_end_date: string | null; meeting_price: number; audience_scope?: "all" | "community"; community_ids?: string[]; meetings?: Meeting[] };
type MentorSubject = { id: number; name: string; category: string };
type Community = { id: string; name: string; locality: string };
type Visibility = { generalScope: "public" | "community_restricted"; parentApprovedScope: "public" | "community_restricted"; communityIds: string[]; isMinor: boolean };
type Form = { weekdays: number[]; startTime: string; endTime: string; meetingMode: string; location: string; meetingPrice: number; durations: number[]; subjectIds: number[]; effectiveStartDate: string; effectiveEndDate: string; audienceScope: "all" | "community"; communityIds: string[] };
const freshForm = (): Form => ({ weekdays: [0], startTime: "16:00", endTime: "18:00", meetingMode: "פרונטלי", location: "", meetingPrice: 0, durations: [60], subjectIds: [], effectiveStartDate: "", effectiveEndDate: "", audienceScope: "all", communityIds: [] });

export default function SchedulingAvailabilityPage() {
  const [token, setToken] = useState(""); const [windows, setWindows] = useState<WindowRow[]>([]); const [subjects, setSubjects] = useState<MentorSubject[]>([]); const [communities, setCommunities] = useState<Community[]>([]); const [visibility, setVisibility] = useState<Visibility | null>(null);
  const [editingId, setEditingId] = useState(""); const [historyId, setHistoryId] = useState(""); const [showInactive, setShowInactive] = useState(false);
  const [capabilities, setCapabilities] = useState<{ age: number | null; isAdult: boolean }>({ age: null, isAdult: false }); const [form, setForm] = useState<Form>(freshForm()); const [customDuration, setCustomDuration] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);

  async function load(accessToken: string) {
    const headers = { Authorization: `Bearer ${accessToken}` };
    const [response, subjectResponse, communityResponse, visibilityResponse] = await Promise.all([fetch("/api/mentor-availability", { headers, cache: "no-store" }), fetch("/api/mentor-subjects", { headers, cache: "no-store" }), fetch("/api/communities", { headers, cache: "no-store" }), fetch("/api/mentor-visibility", { headers, cache: "no-store" })]);
    const [body, subjectBody, communityBody, visibilityBody] = await Promise.all([response.json().catch(() => ({})), subjectResponse.json().catch(() => ({})), communityResponse.json().catch(() => ({})), visibilityResponse.json().catch(() => ({}))]);
    if (!response.ok || !subjectResponse.ok || !communityResponse.ok || !visibilityResponse.ok) { setMessage(body.error ?? subjectBody.error ?? communityBody.error ?? visibilityBody.error ?? "לא ניתן לטעון את הזמינות."); return; }
    setWindows(body.windows ?? []); setCapabilities(body.capabilities ?? { age: null, isAdult: false }); setCommunities(communityBody.communities ?? []); setVisibility(visibilityBody);
    const selectedIds = new Set<number>((subjectBody.selected ?? []).map((item: { subject_id: number }) => item.subject_id)); setSubjects((subjectBody.catalog ?? []).filter((subject: MentorSubject) => selectedIds.has(subject.id)));
  }
  useEffect(() => { void supabase.auth.getSession().then(({ data }) => { const accessToken = data.session?.access_token ?? ""; setToken(accessToken); if (accessToken) void load(accessToken); }); }, []);

  const allowedCommunities = useMemo(() => visibility?.generalScope === "community_restricted" ? communities.filter((c) => visibility.communityIds.includes(c.id)) : communities, [communities, visibility]);
  const canPublic = Boolean(visibility && visibility.generalScope === "public" && (!visibility.isMinor || visibility.parentApprovedScope === "public"));

  async function save() {
    if (busy) return; if (form.endTime <= form.startTime || !form.durations.length || !form.subjectIds.length || !form.weekdays.length) { setMessage("יש להשלים יום, שעות, משך ומקצוע."); return; }
    if (form.meetingMode === "פרונטלי" && !form.location.trim()) { setMessage("יש להזין מיקום לזמינות פרונטלית."); return; }
    if (form.audienceScope === "community" && !form.communityIds.length) { setMessage("יש לבחור לפחות קהילה אחת."); return; }
    setBusy(true); setMessage("");
    try { for (const weekday of form.weekdays) { const response = await fetch("/api/mentor-availability", { method: editingId ? "PATCH" : "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ ...form, weekday, id: editingId || undefined }) }); const body = await response.json().catch(() => ({})); if (!response.ok) { setMessage(body.error ?? "לא ניתן לשמור את הזמינות."); return; } } setEditingId(""); setForm(freshForm()); await load(token); setMessage("הזמינות נשמרה בהצלחה."); }
    finally { setBusy(false); }
  }
  async function patch(window: WindowRow, extra: Record<string, unknown>) { await fetch("/api/mentor-availability", { method: "PATCH", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ id: window.id, weekday: window.weekday, startTime: window.start_time.slice(0,5), endTime: window.end_time.slice(0,5), meetingMode: window.meeting_mode, location: window.location ?? "", meetingPrice: window.meeting_price, durations: window.supported_durations, subjectIds: window.subject_ids, effectiveStartDate: window.effective_start_date ?? "", effectiveEndDate: window.effective_end_date ?? "", audienceScope: window.audience_scope ?? "all", communityIds: window.community_ids ?? [], ...extra }) }); await load(token); }
  async function remove(id: string) { if (!confirm("למחוק את הזמינות?")) return; const response = await fetch(`/api/mentor-availability?id=${id}&type=window`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); if (response.ok) await load(token); }
  function edit(window: WindowRow) { setEditingId(window.id); setForm({ weekdays:[window.weekday], startTime:window.start_time.slice(0,5), endTime:window.end_time.slice(0,5), meetingMode:window.meeting_mode, location:window.location ?? "", meetingPrice:window.meeting_price ?? 0, durations:window.supported_durations, subjectIds:window.subject_ids, effectiveStartDate:window.effective_start_date ?? "", effectiveEndDate:window.effective_end_date ?? "", audienceScope:window.audience_scope ?? "all", communityIds:window.community_ids ?? [] }); globalThis.scrollTo?.({ top: 0, behavior: "smooth" }); }
  const active = windows.filter(w => w.is_active), inactive = windows.filter(w => !w.is_active);

  return <MentorPageShell title="הזמינות שלי" description="מגדירים מתי, איפה ולמי אפשר לבקש פגישה.">
    {message && <p className="mb-4 rounded-xl bg-blue-50 p-3 font-bold text-blue-900">{message}</p>}
    <section className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">{editingId ? "עריכת זמינות" : "זמינות חדשה"}</h2>
      <div className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <Field label="ימים"><div className="flex flex-wrap gap-2">{DAYS.map((day,i)=><Pill key={day} checked={form.weekdays.includes(i)} label={day} onClick={()=>setForm({...form,weekdays:form.weekdays.includes(i)?form.weekdays.filter(x=>x!==i):[...form.weekdays,i]})}/>)}</div></Field>
        <Field label="משעה"><input type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})} className="input"/></Field><Field label="עד שעה"><input type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})} className="input"/></Field>
        <Field label="אופן פגישה"><select value={form.meetingMode} onChange={e=>setForm({...form,meetingMode:e.target.value,location:e.target.value==="אונליין"?"":form.location})} className="input"><option>פרונטלי</option><option>אונליין</option></select></Field>
        {form.meetingMode === "פרונטלי" && <Field label="מיקום"><input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} placeholder="לדוגמה: ספורטק הוד השרון" className="input"/></Field>}
        <Field label="עלות לפגישה"><input type="number" min="0" value={form.meetingPrice} onChange={e=>setForm({...form,meetingPrice:Number(e.target.value)})} className="input"/></Field>
        <Field label="למי הזמינות פתוחה?"><select value={form.audienceScope} onChange={e=>setForm({...form,audienceScope:e.target.value as "all"|"community",communityIds:[]})} className="input"><option value="all" disabled={!canPublic}>🌐 ציבורי / כל MentorLink</option><option value="community">🔒 קהילה/קהילות</option></select>{!canPublic && <small className="text-amber-800">חשיפה ציבורית דורשת הרשאה מתאימה. ניתן לבקש הרחבת הרשאה דרך החשבון שלי.</small>}</Field>
        {form.audienceScope === "community" && <Field label="קהילות"><div className="flex flex-wrap gap-2">{allowedCommunities.map(c=><Pill key={c.id} checked={form.communityIds.includes(c.id)} label={`${c.name}${c.locality?` · ${c.locality}`:""}`} onClick={()=>setForm({...form,communityIds:form.communityIds.includes(c.id)?form.communityIds.filter(x=>x!==c.id):[...form.communityIds,c.id]})}/>)}</div></Field>}
        <Field label="משכי פגישה"><div className="flex flex-wrap gap-2">{DURATIONS.map(d=><Pill key={d} checked={form.durations.includes(d)} label={`${d} דק׳`} onClick={()=>setForm({...form,durations:form.durations.includes(d)?form.durations.filter(x=>x!==d):[...form.durations,d]})}/>)}</div><div className="mt-2 flex gap-2"><input value={customDuration} onChange={e=>setCustomDuration(e.target.value)} placeholder="משך אחר" className="input"/><button type="button" className="btn" onClick={()=>{const n=Number(customDuration);if(n>=10&&n<=240)setForm({...form,durations:[...new Set([...form.durations,n])].sort((a,b)=>a-b)});setCustomDuration("")}}>הוסף</button></div></Field>
        <Field label="מקצועות"><div className="flex flex-wrap gap-2">{subjects.map(s=><Pill key={s.id} checked={form.subjectIds.includes(s.id)} label={s.name} onClick={()=>setForm({...form,subjectIds:form.subjectIds.includes(s.id)?form.subjectIds.filter(x=>x!==s.id):[...form.subjectIds,s.id]})}/>)}</div></Field>
      </div><div className="mt-5 flex gap-2"><button disabled={busy} onClick={save} className="rounded-xl bg-blue-700 px-5 py-3 font-black text-white disabled:opacity-50">{busy?"שומר...":editingId?"שמור שינויים":"הוסף זמינות"}</button>{editingId&&<button onClick={()=>{setEditingId("");setForm(freshForm())}} className="btn">ביטול</button>}</div>
    </section>
    <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{active.map(w=><AvailabilityCard key={w.id} window={w} communities={communities} subjects={subjects} historyOpen={historyId===w.id} onHistory={()=>setHistoryId(historyId===w.id?"":w.id)} onEdit={()=>edit(w)} onToggle={()=>patch(w,{isActive:false})} onDelete={()=>remove(w.id)}/>)}</div>
    {inactive.length>0&&<section className="mt-6"><button onClick={()=>setShowInactive(!showInactive)} className="font-black text-slate-700">{showInactive?"▾":"◂"} זמינויות לא פעילות ({inactive.length})</button>{showInactive&&<div className="mt-3 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{inactive.map(w=><AvailabilityCard key={w.id} window={w} communities={communities} subjects={subjects} historyOpen={historyId===w.id} onHistory={()=>setHistoryId(historyId===w.id?"":w.id)} onEdit={()=>edit(w)} onToggle={()=>patch(w,{isActive:true})} onDelete={()=>remove(w.id)}/>)}</div>}</section>}
    <style jsx global>{`.input{width:100%;border:1px solid #cbd5e1;border-radius:.75rem;padding:.7rem;background:white}.btn{border:1px solid #cbd5e1;border-radius:.75rem;padding:.7rem 1rem;font-weight:800;background:white}`}</style>
  </MentorPageShell>;
}
function AvailabilityCard({window,communities,subjects,historyOpen,onHistory,onEdit,onToggle,onDelete}:{window:WindowRow;communities:Community[];subjects:MentorSubject[];historyOpen:boolean;onHistory:()=>void;onEdit:()=>void;onToggle:()=>void;onDelete:()=>void}) { const meetings=window.meetings??[]; const upcoming=meetings.filter(m=>!["cancelled","declined"].includes(m.status)&&new Date(m.confirmed_start_at??m.requested_start_at)>new Date()).length; const completed=meetings.filter(m=>new Date(m.confirmed_start_at??m.requested_start_at)<new Date()&&!["cancelled","declined"].includes(m.status)).length; const names=(window.community_ids??[]).map(id=>communities.find(c=>c.id===id)?.name).filter(Boolean).join(", "); return <article className="rounded-3xl border bg-white p-5 shadow-sm"><p className="text-lg font-black">{DAYS[window.weekday]} · {window.start_time.slice(0,5)}–{window.end_time.slice(0,5)}</p><p className="mt-1 text-slate-700">{window.meeting_mode} · {window.supported_durations.join(", ")} דקות</p>{window.location&&<p className="text-slate-700">📍 {window.location}</p>}<p className="mt-2 font-bold">{window.audience_scope==="community"?`🔒 ${names||"קהילה"}`:"🌐 ציבורי"}</p><p className="mt-2 text-sm">{subjects.filter(s=>window.subject_ids.includes(s.id)).map(s=>s.name).join(", ")}</p><p className="mt-2 font-bold text-emerald-800">{window.meeting_price?`${window.meeting_price} ₪` : "ללא עלות"}</p><button onClick={onHistory} className="mt-3 text-sm font-black text-blue-700">{upcoming} פגישות קרובות · {completed} התקיימו</button>{historyOpen&&<div className="mt-3 border-t pt-3">{meetings.length?meetings.map(m=><div key={m.id} className="border-b py-2 text-sm"><b>{new Date(m.confirmed_start_at??m.requested_start_at).toLocaleString("he-IL")}</b> · {m.child_first_name} · {m.subject}<div>{m.status}</div></div>):<p className="text-sm text-slate-500">עדיין אין פגישות מזמינות זו.</p>}</div>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={onEdit} className="btn">עריכה</button><button onClick={onToggle} className="btn">{window.is_active?"השבתה":"הפעלה"}</button><button onClick={onDelete} className="rounded-xl border border-red-200 px-3 py-2 text-sm font-bold text-red-700">מחיקה</button></div></article> }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="grid content-start gap-2 font-bold">{label}{children}</label> }
function Pill({checked,label,onClick}:{checked:boolean;label:string;onClick:()=>void}) { return <button type="button" onClick={onClick} className={`rounded-full border px-3 py-2 text-sm font-bold ${checked?"bg-slate-900 text-white":"bg-white"}`}>{label}</button> }
