"use client";
import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
type Inquiry={id:string;subject:string|null;child_grade_or_age:string|null;message:string;status:string;mentor_response:string|null;created_at:string};
const activeStatuses=["pending","responded"];
export default function MentorGeneralInquiriesPanel(){
 const[token,setToken]=useState(""),[items,setItems]=useState<Inquiry[]>([]),[loadState,setLoadState]=useState<"loading"|"loaded"|"error">("loading"),[responses,setResponses]=useState<Record<string,string>>({}),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async(accessToken:string)=>{setLoadState("loading");try{const response=await fetch("/api/mentor-inquiries",{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error("INQUIRIES_LOAD_FAILED");setItems(body.inquiries??[]);setLoadState("loaded")}catch{setLoadState("error")}},[]);
 useEffect(()=>{void supabase.auth.getSession().then(({data})=>{const accessToken=data.session?.access_token??"";setToken(accessToken);if(accessToken)void load(accessToken);else setLoadState("error")})},[load]);
 async function act(id:string,action:"respond"|"close"){if(!confirm("להמשיך בפעולה?"))return;setBusy(id);const response=await fetch(`/api/mentor-inquiries/${id}`,{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({action,response:responses[id]??""})});const body=await response.json().catch(()=>({}));setMessage(response.ok?"הפנייה עודכנה.":body.error??"לא ניתן לעדכן את הפנייה.");if(response.ok)await load(token);setBusy("")}
 if(loadState==="loading")return <p role="status" className="mt-8 rounded-2xl bg-white p-5 font-bold text-slate-600">טוען פניות...</p>;
 if(loadState==="error")return <div role="alert" className="mt-8 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-800"><p className="font-bold">לא ניתן לטעון את הפניות כרגע.</p><button type="button" disabled={!token} onClick={()=>void load(token)} className="mt-3 rounded-xl border border-red-300 bg-white px-4 py-2 font-bold disabled:opacity-50">ניסיון נוסף</button></div>;
 const active=items.filter((item)=>activeStatuses.includes(item.status)),handled=items.filter((item)=>!activeStatuses.includes(item.status));
 return <section className="mt-8"><InquirySection id="active-inquiries" title="פניות פעילות" items={active} empty="אין פניות פעילות." busy={busy} responses={responses} setResponses={setResponses} act={act}/><InquirySection title="פניות שטופלו" items={handled} empty="אין פניות שטופלו." busy={busy} responses={responses} setResponses={setResponses} act={act}/>{message&&<p role="status" className="mt-4 rounded-xl bg-blue-50 p-3 font-bold">{message}</p>}</section>
}
function InquirySection({id,title,items,empty,busy,responses,setResponses,act}:{id?:string;title:string;items:Inquiry[];empty:string;busy:string;responses:Record<string,string>;setResponses:React.Dispatch<React.SetStateAction<Record<string,string>>>;act:(id:string,action:"respond"|"close")=>Promise<void>}){
 return <section id={id} aria-labelledby={`inquiry-${title}`} className="mb-8 scroll-mt-24"><h2 id={`inquiry-${title}`} className="text-2xl font-black">{title}</h2>{!items.length?<p className="mt-3 rounded-2xl bg-white p-5 text-slate-600">{empty}</p>:<div className="mt-3 grid gap-4">{items.map((item)=><article key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-black">{item.subject||"פנייה כללית"}</h3><span className="rounded-full bg-blue-50 px-3 py-1 text-sm font-bold text-blue-800">{activeStatuses.includes(item.status)?"פעילה":item.status==="closed"?"טופלה":"בוטלה"}</span></div>{item.child_grade_or_age&&<p className="mt-2 text-sm text-slate-600">כיתה או גיל: {item.child_grade_or_age}</p>}<p className="mt-3 whitespace-pre-wrap rounded-xl bg-slate-50 p-4">{item.message}</p>{item.mentor_response&&<p className="mt-3 whitespace-pre-wrap rounded-xl bg-green-50 p-4"><strong>התשובה שלך: </strong>{item.mentor_response}</p>}{activeStatuses.includes(item.status)&&<div className="mt-4 flex flex-wrap gap-2"><textarea aria-label="תשובה לפנייה" value={responses[item.id]??""} onChange={(event)=>setResponses((current)=>({...current,[item.id]:event.target.value}))} maxLength={1000} className="min-h-20 w-full rounded-xl border p-3"/><button type="button" disabled={busy===item.id||(responses[item.id]??"").trim().length<2} onClick={()=>void act(item.id,"respond")} className="rounded-xl bg-blue-700 px-4 py-2 font-bold text-white disabled:opacity-50">שליחת תשובה</button><button type="button" disabled={busy===item.id} onClick={()=>void act(item.id,"close")} className="rounded-xl border px-4 py-2 font-bold">סימון הפנייה כטופלה</button></div>}</article>)}</div>}</section>
}
