"use client";
import Link from "next/link";
import Image from "next/image";
import { usePathname, useRouter } from "next/navigation";
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { getDashboardPath } from "@/lib/auth-routing";
import { supabase } from "@/lib/supabase";
import { isActiveGeneralInquiry, isUpcomingApprovedMeeting, requiresMentorAction, waitsForParentAction } from "@/lib/mentor-dashboard-status";

export const mentorNavigation = [
 {href:"/dashboard/mentor",label:"עמוד הבית"},
 {href:"/dashboard/mentor/meetings",label:"בקשות ופגישות",badge:"meetings"},
 {href:"/dashboard/mentor/inquiries",label:"פניות מהורים",badge:"inquiries"},
 {href:"/dashboard/mentor/scheduling",label:"הזמינות שלי"},
 {href:"/dashboard/mentor/subjects",label:"המקצועות והתחומים שלי"},
 {href:"/dashboard/mentor/activities/new",label:"פתיחת פעילות חדשה"},
 {href:"/dashboard/mentor/activities",label:"הפעילויות שלי"},
 {href:"/dashboard/mentor/activity-registrations",label:"הרשמות לפעילויות",badge:"activityRegistrations"},
 {href:"/dashboard/mentor/feedback",label:"משובים שקיבלתי"},
 {href:"/dashboard/mentor/discover",label:"חיפוש חונכים ופעילויות"},
 {href:"/dashboard/mentor/account",label:"החשבון שלי"},
] as const;
type Summary={mentorActionMeetings:number;waitingForParent:number;activeInquiries:number;activityRegistrations:number;upcomingMeetings:number;availabilityConfigured:boolean|null;profileConfigured:boolean|null;summaryState:"loading"|"loaded"|"error"};
const empty:Summary={mentorActionMeetings:0,waitingForParent:0,activeInquiries:0,activityRegistrations:0,upcomingMeetings:0,availabilityConfigured:null,profileConfigured:null,summaryState:"loading"};
const Context=createContext(empty);
export function useMentorDashboard(){return useContext(Context)}

type ImportantNoticeDetails={type:"meeting"|"activity";parentName?:string;mentorName?:string;childName?:string;childGrade?:string;subject?:string;meetingMode?:string;activityTitle?:string;registrationStatus?:string;startsAt?:string|null;endsAt?:string|null;durationMinutes?:number|null;location?:string|null;reason?:string|null};
type ImportantNotice={id:string;kind:string;title:string;body:string;href:string|null;read_at:string|null;created_at:string;details?:ImportantNoticeDetails};
const importantMeetingKinds=new Set(["meeting_request_created","meeting_request_cancelled","meeting_request_accepted","meeting_request_declined"]);
export function MentorImportantUpdates({scope}:{scope:"meetings"|"activities"}){
 const[rows,setRows]=useState<ImportantNotice[]>([]),[token,setToken]=useState("");
 const load=useCallback(async(accessToken:string)=>{const response=await fetch("/api/notifications",{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"});if(!response.ok)return;const body=await response.json();setRows((body.notifications??[]).filter((item:ImportantNotice)=>scope==="meetings"?importantMeetingKinds.has(item.kind):item.title==="ביטול הרשמה לפעילות"||item.title==="ביטול השתתפות בפעילות"));},[scope]);
 useEffect(()=>{void supabase.auth.getSession().then(({data})=>{const accessToken=data.session?.access_token??"";setToken(accessToken);if(accessToken)void load(accessToken);});},[load]);
 const unread=useMemo(()=>rows.filter(row=>!row.read_at),[rows]),history=useMemo(()=>rows.filter(row=>row.read_at),[rows]);
 async function markRead(id:string){const response=await fetch("/api/notifications",{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({notificationId:id})});if(response.ok){await load(token);window.dispatchEvent(new Event("mentorlink:mentor-summary-refresh"));}}
 if(!rows.length)return null;
 return <section className="mb-8 rounded-3xl border border-amber-300 bg-amber-50/80 p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div><p className="font-black text-amber-800">חשוב לדעת</p><h2 className="text-2xl font-black">עדכונים חשובים מההורים</h2></div>{unread.length>0&&<span className="rounded-full bg-red-600 px-3 py-1 font-black text-white">{unread.length}</span>}</div><ImportantNoticeList rows={unread} empty="אין עדכונים חדשים." markRead={markRead}/>{history.length>0&&<details className="mt-4 rounded-2xl border bg-white p-4"><summary className="cursor-pointer font-black">עדכונים שקראתי ({history.length})</summary><ImportantNoticeList rows={history} markRead={markRead}/></details>}</section>;
}
function ImportantNoticeList({rows,empty,markRead}:{rows:ImportantNotice[];empty?:string;markRead:(id:string)=>Promise<void>}){if(!rows.length)return empty?<p className="mt-4 rounded-xl bg-white p-4 text-slate-600">{empty}</p>:null;return <div className="mt-4 grid gap-3">{rows.map(row=><article key={row.id} className="rounded-2xl border border-red-200 bg-white p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><span className="rounded-full bg-red-600 px-3 py-1 text-xs font-black text-white">עדכון חשוב</span><h3 className="mt-2 text-lg font-black">{row.title}</h3></div><time className="text-sm font-bold text-slate-600">{new Date(row.created_at).toLocaleString("he-IL")}</time></div><p className="mt-3 text-base font-semibold leading-7 text-slate-900">{row.body}</p>{row.details?<ImportantNoticeDetailsBox details={row.details}/>:null}{!row.read_at&&<button type="button" onClick={()=>void markRead(row.id)} className="mt-3 rounded-xl bg-violet-700 px-4 py-2 font-black text-white">קראתי — העברה להיסטוריה</button>}</article>)}</div>}
function ImportantNoticeDetailsBox({details}:{details:ImportantNoticeDetails}){const date=details.startsAt?new Intl.DateTimeFormat("he-IL",{timeZone:"Asia/Jerusalem",dateStyle:"full",timeStyle:"short"}).format(new Date(details.startsAt)):null;return <dl className="mt-4 grid gap-2 rounded-2xl border border-red-200 bg-red-50/70 p-4 text-base text-slate-950 sm:grid-cols-2"><div><dt className="font-black">{details.type==="meeting"?"הילד/ה":"הילד/ה שנרשמ/ה"}</dt><dd>{details.childName??"לא צוין"}{details.childGrade?` · ${details.childGrade}`:""}</dd></div><div><dt className="font-black">הורה</dt><dd>{details.parentName??"לא צוין"}</dd></div>{details.type==="meeting"?<><div><dt className="font-black">נושא ותחום</dt><dd>{details.subject??"לא צוין"}{details.meetingMode?` · ${details.meetingMode}`:""}</dd></div><div><dt className="font-black">חונך/ת</dt><dd>{details.mentorName??"החשבון שלך"}</dd></div></>:<div><dt className="font-black">פעילות</dt><dd>{details.activityTitle??"לא צוין"} · {details.registrationStatus==="waitlisted"?"רשימת המתנה":"רישום לפעילות"}</dd></div>}<div><dt className="font-black">יום, תאריך ושעה</dt><dd>{date??"לא נקבע"}{details.durationMinutes?` · ${details.durationMinutes} דקות`:""}</dd></div><div><dt className="font-black">מיקום</dt><dd>{details.location??"טרם נקבע"}</dd></div>{details.reason?<div className="sm:col-span-2"><dt className="font-black">סיבת הביטול</dt><dd>{details.reason}</dd></div>:null}</dl>}

export default function MentorDashboardShell({children}:{children:React.ReactNode}){
 const pathname=usePathname(),router=useRouter();const[ready,setReady]=useState(false),[name,setName]=useState(""),[email,setEmail]=useState(""),[summary,setSummary]=useState(empty),[accountControl,setAccountControl]=useState<{status:"active"|"suspended"|"blocked";reason:string|null;suspendedUntil:string|null}|null>(null);
 useEffect(()=>{let active=true;async function load(){
  const{data}=await supabase.auth.getUser();if(!active)return;if(!data.user){router.replace("/login");return}
  const destination=await getDashboardPath(data.user.id);if(!active)return;const registrationSupportRoute=pathname==="/dashboard/mentor/parent-consent"&&data.user.user_metadata?.role==="mentor";if(destination!=="/dashboard/mentor"&&!registrationSupportRoute){router.replace(destination);return}
  setName(data.user.user_metadata?.first_name??"");setEmail(data.user.email??data.user.phone??"");
  const token=(await supabase.auth.getSession()).data.session?.access_token;if(token){const headers={Authorization:`Bearer ${token}`};const accountResponse=await fetch("/api/mentor-account-status",{headers,cache:"no-store"}).catch(()=>new Response(null,{status:503}));if(accountResponse.ok){const account=await accountResponse.json();if(account.status!=="active"){setAccountControl(account);if(active)setReady(true);return}}const safeFetch=(input:string,init:RequestInit)=>fetch(input,init).catch(()=>new Response(null,{status:503}));const responses=await Promise.all([safeFetch("/api/meeting-requests",{headers,cache:"no-store"}),safeFetch("/api/mentor-inquiries",{headers,cache:"no-store"}),safeFetch("/api/mentor-availability",{headers,cache:"no-store"}),safeFetch("/api/mentor-profile",{headers,cache:"no-store"}),safeFetch("/api/notifications",{headers,cache:"no-store"}),safeFetch("/api/mentor-activity-registrations",{headers,cache:"no-store"})]);const bodies=await Promise.all(responses.map((response)=>response.ok?response.json():Promise.resolve({})));const meetings=bodies[0].requests??[],inquiries=bodies[1].inquiries??[],actionMeetingIds=meetings.filter(requiresMentorAction).map((item:{id:string})=>item.id),attentionMeetingIds=bodies[0].unreadMeetingIds??[],now=Date.now();setSummary({
   mentorActionMeetings:new Set([...actionMeetingIds,...attentionMeetingIds]).size,
   waitingForParent:meetings.filter(waitsForParentAction).length,
   activeInquiries:inquiries.filter(isActiveGeneralInquiry).length,
   activityRegistrations:(bodies[5].registrations??[]).length,
   upcomingMeetings:meetings.filter((item:{status:string;confirmed_start_at?:string|null})=>isUpcomingApprovedMeeting(item,now)).length,
   availabilityConfigured:responses[2].ok?(bodies[2].windows??[]).some((item:{is_active?:boolean})=>item.is_active!==false):null,
   profileConfigured:responses[3].ok?Boolean(bodies[3].profile?.first_name&&bodies[3].profile?.bio):null,
   summaryState:responses[0].ok&&responses[1].ok?"loaded":"error",
  })}
  if(active)setReady(true)
 }void load();return()=>{active=false}},[router,pathname]);
 useEffect(()=>{void supabase.auth.getUser().then(({data})=>{if(data.user?.user_metadata?.must_change_password)router.replace("/account/change-password")})},[router]);
 useEffect(()=>{const close=(event:PointerEvent)=>{document.querySelectorAll<HTMLDetailsElement>("details[data-mobile-menu][open]").forEach((menu)=>{if(!menu.contains(event.target as Node))menu.removeAttribute("open")})};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close)},[]);
 if(!ready)return <main dir="rtl" className="grid min-h-screen place-items-center bg-slate-50"><p role="status" className="font-bold text-slate-600">טוען את אזור החונכים...</p></main>;
 if(accountControl)return <main dir="rtl" className="grid min-h-screen place-items-center bg-slate-50 p-5"><section className="w-full max-w-xl rounded-3xl border border-red-200 bg-white p-8 text-center shadow-xl"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-red-100 text-3xl">!</div><h1 className="mt-5 text-3xl font-black">{accountControl.status==="blocked"?"החשבון נחסם":"החשבון מושבת זמנית"}</h1><p className="mt-3 text-slate-600">הגישה לאזור החונכים אינה זמינה כרגע.</p>{accountControl.reason?<p className="mt-4 rounded-xl bg-slate-100 p-4"><b>סיבה:</b> {accountControl.reason}</p>:null}{accountControl.suspendedUntil?<p className="mt-3 font-bold">ההשבתה נקבעה עד {new Date(accountControl.suspendedUntil).toLocaleString("he-IL",{timeZone:"Asia/Jerusalem"})}</p>:null}<p className="mt-5 text-sm text-slate-500">לבירור ניתן לפנות למנהל MentorLink.</p><button onClick={async()=>{await supabase.auth.signOut();router.push("/login")}} className="mt-6 rounded-xl bg-slate-900 px-6 py-3 font-bold text-white">התנתקות</button></section></main>;
 const nav=(mobile=false)=><nav aria-label={mobile?"ניווט חונכים בנייד":"ניווט חונכים"} className="grid gap-1">{mentorNavigation.map((item)=>{const exact=item.href==="/dashboard/mentor"||item.href==="/dashboard/mentor/activities";const selected=exact?pathname===item.href:pathname.startsWith(item.href);const badge="badge" in item?item.badge:undefined;const count=badge==="meetings"?summary.mentorActionMeetings:badge==="inquiries"?summary.activeInquiries:badge==="activityRegistrations"?summary.activityRegistrations:0;return <Link key={item.href} href={item.href} onClick={(event)=>{if(mobile)event.currentTarget.closest("details")?.removeAttribute("open")}} aria-current={selected?"page":undefined} className={`flex min-h-12 items-center justify-between gap-3 rounded-xl px-4 py-3 font-bold transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 ${selected?"bg-blue-700 text-white":"text-slate-700 hover:bg-blue-50 hover:text-blue-800"}`}><span>{item.label}</span>{count>0&&<span aria-label={`${count} פריטים דורשים תשומת לב`} className={`rounded-full px-2 py-0.5 text-xs font-black ${selected?"bg-white text-blue-800":"bg-amber-500 text-slate-950"}`}>{count}</span>}</Link>})}</nav>;
 return <Context.Provider value={summary}><div dir="rtl" className="min-h-screen overflow-x-hidden bg-slate-50 text-slate-950">
  <header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[96rem] items-center justify-between gap-4 px-4 py-3 sm:px-6"><Link href="/dashboard/mentor" aria-label="MentorLink – עמוד הבית לחונכים" className="flex items-center"><Image src="/mentorlink-logo.png" alt="MentorLink" width={112} height={64} priority className="h-14 w-auto object-contain" /></Link><div className="flex items-center gap-3"><span className="hidden text-left sm:block"><span className="block font-bold text-slate-700">{name?`שלום, ${name}`:"אזור החונכים"}</span>{email&&<span className="block text-xs text-slate-500">{email}</span>}</span><button type="button" onClick={async()=>{await supabase.auth.signOut();router.push("/login")}} className="min-h-11 rounded-xl border border-slate-300 px-4 py-2 font-bold hover:bg-slate-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600">התנתקות</button><details data-mobile-menu className="relative lg:hidden"><summary aria-label="פתיחת תפריט החונכים" className="cursor-pointer list-none rounded-xl border border-slate-300 px-4 py-2.5 font-black marker:content-none">תפריט</summary><div className="absolute left-0 top-14 w-[min(20rem,calc(100vw-2rem))] rounded-2xl border border-slate-200 bg-white p-3 shadow-2xl">{nav(true)}</div></details></div></div></header>
  <div className="mx-auto grid max-w-[96rem] lg:grid-cols-[18rem_minmax(0,1fr)]"><aside className="sticky top-[69px] hidden h-[calc(100vh-69px)] overflow-y-auto border-l border-slate-200 bg-white p-5 lg:block"><p className="mb-4 px-4 text-sm font-black text-slate-500">האזור האישי לחונכים</p>{nav()}</aside><main className="min-w-0 px-4 py-8 sm:px-6 lg:px-10">{children}</main></div>
 </div></Context.Provider>
}
