"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Child={id:string;first_name:string;last_name:string|null;grade:string|null;birth_date:string|null;school_name:string|null;accommodation_notes:string|null;default_mentor_message:string|null;auto_include_mentor_message:boolean;interests:{subjectId:number;name?:string;category?:string}[]};
type Subject={id:number;name:string;category:string};
const grades:Record<string,string>={kindergarten:"גן חובה",...Object.fromEntries(Array.from({length:12},(_,index)=>[`grade_${index+1}`,index<9?`${String.fromCharCode(1488+index)}׳`:["י׳","י״א","י״ב"][index-9]]))};
const empty={id:"",firstName:"",lastName:"",grade:"",birthDate:"",schoolName:"",accommodationNotes:"",defaultMentorMessage:"",autoIncludeMentorMessage:false,interestSubjectIds:[] as number[]};
const input="min-h-12 rounded-xl border-2 border-slate-400 bg-white p-3 font-semibold text-slate-950 placeholder:text-slate-500 outline-none focus:border-violet-700 focus:ring-4 focus:ring-violet-100";

export default function ParentChildrenManager(){
 const[children,setChildren]=useState<Child[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[form,setForm]=useState(empty),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function token(){return(await supabase.auth.getSession()).data.session?.access_token??""}
 async function load(){const access=await token();const[response,subjectResponse]=await Promise.all([fetch("/api/parent/children",{headers:{Authorization:`Bearer ${access}`},cache:"no-store"}),fetch("/api/parent/subjects",{headers:{Authorization:`Bearer ${access}`},cache:"no-store"})]);if(response.ok)setChildren((await response.json()).children??[]);if(subjectResponse.ok)setSubjects((await subjectResponse.json()).subjects??[]);setLoading(false)}
 useEffect(()=>{void load()},[]);
 async function save(){setBusy(true);setMessage("");const response=await fetch("/api/parent/children",{method:form.id?"PATCH":"POST",headers:{Authorization:`Bearer ${await token()}`,"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json();setBusy(false);if(!response.ok)return setMessage(body.error??"לא ניתן לשמור.");setMessage("הפרטים נשמרו.");setForm(empty);await load()}
 function toggleInterest(id:number){setForm({...form,interestSubjectIds:form.interestSubjectIds.includes(id)?form.interestSubjectIds.filter(value=>value!==id):[...form.interestSubjectIds,id]})}
 return <div className="mt-8 grid gap-7 lg:grid-cols-[1fr_1.2fr]"><div className="rounded-3xl border border-violet-200 bg-violet-50/60 p-6"><h2 className="text-xl font-black">{form.id?"עריכת פרטי ילד/ה":"הוספת ילד/ה"}</h2><div className="mt-5 grid gap-4">
  <label className="grid gap-2 font-extrabold">שם פרטי<input className={input} value={form.firstName} onChange={event=>setForm({...form,firstName:event.target.value})}/></label>
  <label className="grid gap-2 font-extrabold">שם משפחה<input className={input} value={form.lastName} onChange={event=>setForm({...form,lastName:event.target.value})}/></label>
  <label className="grid gap-2 font-extrabold">כיתה או מסגרת (לא חובה)<select className={input} value={form.grade} onChange={event=>setForm({...form,grade:event.target.value})}><option value="">לא צוינה</option>{Object.entries(grades).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
  <label className="grid gap-2 font-extrabold">בית ספר או גן (לא חובה)<input maxLength={120} className={input} value={form.schoolName} onChange={event=>setForm({...form,schoolName:event.target.value})}/></label>
  <label className="grid gap-2 font-extrabold">תאריך לידה (לא חובה)<input type="date" className={input} value={form.birthDate} onChange={event=>setForm({...form,birthDate:event.target.value})}/></label>
  <fieldset className="rounded-2xl border-2 border-slate-300 bg-white p-4"><legend className="px-2 font-black">תחומי עניין ומקצועות</legend><div className="mt-2 flex max-h-52 flex-wrap gap-2 overflow-y-auto">{subjects.map(subject=><button type="button" aria-pressed={form.interestSubjectIds.includes(subject.id)} key={subject.id} onClick={()=>toggleInterest(subject.id)} className={`rounded-full border px-3 py-2 text-sm font-bold ${form.interestSubjectIds.includes(subject.id)?"border-violet-700 bg-violet-700 text-white":"border-slate-400 bg-white text-slate-900"}`}>{subject.name}</button>)}</div></fieldset>
  <label className="grid gap-2 font-extrabold">התאמות שיעזרו להשתתף בבטחה ובנוחות (פרטי, לא חובה)<textarea maxLength={1000} className={input+" min-h-28"} value={form.accommodationNotes} onChange={event=>setForm({...form,accommodationNotes:event.target.value})}/></label>
  <label className="grid gap-2 font-extrabold">הודעה קבועה לחונך<textarea maxLength={1000} className={input+" min-h-28"} placeholder="מידע קצר שיכול לעזור לחונך להכיר את הילד ולהתכונן למפגש" value={form.defaultMentorMessage} onChange={event=>setForm({...form,defaultMentorMessage:event.target.value})}/></label>
  <label className="flex items-start gap-3 rounded-2xl border bg-white p-4 font-bold"><input type="checkbox" className="mt-1 size-5" checked={form.autoIncludeMentorMessage} onChange={event=>setForm({...form,autoIncludeMentorMessage:event.target.checked})}/><span>לצרף את ההודעה אוטומטית לבקשות חדשות עבור הילד הזה.<small className="mt-1 block font-normal text-slate-600">אפשר לערוך או למחוק אותה לפני השליחה.</small></span></label>
  <button disabled={busy||!form.firstName.trim()} onClick={save} className="rounded-xl bg-violet-700 p-3 font-black text-white disabled:bg-slate-300">{busy?"שומר...":"שמירת הפרטים"}</button>{form.id&&<button onClick={()=>setForm(empty)} className="font-bold text-slate-700 underline">ביטול עריכה</button>}{message&&<p role="status" className="rounded-xl bg-white p-3 font-bold">{message}</p>}
 </div></div><div><h2 className="text-xl font-black">הילדים בחשבון</h2>{loading?<p className="mt-4">טוען...</p>:children.length?<div className="mt-4 grid gap-3">{children.map(child=><article key={child.id} className="flex items-center justify-between gap-4 rounded-2xl border bg-white p-5"><div><h3 className="text-lg font-black">{[child.first_name,child.last_name].filter(Boolean).join(" ")}</h3><p className="text-slate-600">{child.grade?(child.grade==="kindergarten"?grades[child.grade]:`כיתה ${grades[child.grade]}`):"כיתה לא צוינה"}{child.school_name?` · ${child.school_name}`:""}</p>{child.interests?.length>0&&<p className="mt-1 text-sm font-bold text-violet-700">{child.interests.map(interest=>interest.name).filter(Boolean).join(" · ")}</p>}</div><button onClick={()=>setForm({id:child.id,firstName:child.first_name,lastName:child.last_name??"",grade:child.grade??"",birthDate:child.birth_date??"",schoolName:child.school_name??"",accommodationNotes:child.accommodation_notes??"",defaultMentorMessage:child.default_mentor_message??"",autoIncludeMentorMessage:child.auto_include_mentor_message??false,interestSubjectIds:child.interests?.map(interest=>interest.subjectId)??[]})} className="rounded-xl border border-blue-300 px-4 py-2 font-bold text-blue-700">עריכה</button></article>)}</div>:<p className="mt-4 rounded-2xl border border-dashed bg-white p-6 text-slate-600">עדיין לא נוספו ילדים לחשבון.</p>}</div></div>
}
