"use client";
import { useEffect,useState } from "react";
import { supabase } from "@/lib/supabase";

type Task={registrationId:string;activityTitle:string;childName:string};
type SubmittedFeedback={id:string;registration_id:string;submitted_at:string;activityTitle:string;childName:string;professionalism:number;patience_listening:number;clarity:number;recommendation:number;worked_well:string|null;could_improve:string|null};
const questions=[['professionalism','מקצועיות ואחריות'],['patienceListening','סבלנות והקשבה'],['clarity','בהירות ההסבר'],['ageLevelFit','התאמה לגיל ולרמה'],['childEnjoyment','הנאה של הילד/ה'],['expectations','עמידה בציפיות'],['recommendation','היית ממליץ/ה על החונך']] as const;
const labels=['','כלל לא','במידה מועטה','במידה בינונית','במידה רבה','במידה רבה מאוד'];
const initial={attendance:'attended',professionalism:0,patienceListening:0,clarity:0,ageLevelFit:0,childEnjoyment:0,expectations:0,recommendation:0,punctuality:'on_time',workedWell:'',couldImprove:'',feltUncomfortable:false,safetyIncident:false,requestsAdminContact:false,privateSafetyDetails:'',allowPublicQuote:false};

export default function ParentFeedbackPage(){
 const[tasks,setTasks]=useState<Task[]>([]),[submitted,setSubmitted]=useState<SubmittedFeedback[]>([]),[selected,setSelected]=useState<Task|null>(null),[form,setForm]=useState(initial),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function token(){return(await supabase.auth.getSession()).data.session?.access_token??''}
 async function load(){const response=await fetch('/api/parent/activity-feedback',{headers:{Authorization:`Bearer ${await token()}`},cache:'no-store'});if(response.ok){const body=await response.json();const nextTasks:Task[]=body.tasks??[];setTasks(nextTasks);setSubmitted(body.feedback??[]);const requested=new URLSearchParams(window.location.search).get('registrationId');if(requested)setSelected(nextTasks.find(task=>task.registrationId===requested)??null)}setLoading(false)}
 // Loading starts after mount so the effect itself only schedules external synchronization.
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[]); // eslint-disable-line react-hooks/exhaustive-deps
 async function submit(){if(!selected||questions.some(([key])=>Number(form[key])<1))return setMessage('יש להשלים את כל הדירוגים.');setBusy(true);const response=await fetch('/api/parent/activity-feedback',{method:'POST',headers:{Authorization:`Bearer ${await token()}`,'Content-Type':'application/json'},body:JSON.stringify({...form,registrationId:selected.registrationId})});const body=await response.json().catch(()=>({}));setBusy(false);if(!response.ok)return setMessage(body.error??'לא ניתן לשמור את המשוב.');setMessage('תודה, המשוב נשמר. החלק המקצועי נשלח לחונך והחלק הבטיחותי זמין למנהל בלבד.');setSelected(null);setForm(initial);await load()}
 return <section className="mx-auto max-w-5xl"><p className="font-black text-violet-700">עוזרים לקהילה להשתפר</p><h1 className="mt-2 text-3xl font-black">משובים להשלמה</h1><p className="mt-3 text-slate-700">המשוב אינו חובה ואינו חוסם שימוש באתר. הערות בטיחות נשמרות למנהל בלבד.</p>{message&&<p role="status" className="mt-4 rounded-xl bg-violet-50 p-4 font-bold text-violet-900">{message}</p>}{loading?<p className="mt-7 rounded-2xl bg-white p-6">טוען...</p>:tasks.length?<div className="mt-7 grid gap-4">{tasks.map(task=><article key={task.registrationId} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border bg-white p-5"><div><h2 className="text-xl font-black">{task.activityTitle}</h2><p className="text-slate-600">עבור {task.childName}</p></div><button onClick={()=>{setSelected(task);setMessage('')}} className="rounded-xl bg-violet-700 px-5 py-3 font-black text-white">מילוי משוב</button></article>)}</div>:<p className="mt-7 rounded-2xl border border-dashed bg-white p-8 text-center font-bold text-slate-600">אין כרגע משובים שממתינים להשלמה.</p>}
 {submitted.length>0&&<section className="mt-10"><h2 className="text-2xl font-black">המשובים שמילאתי</h2><p className="mt-2 text-slate-600">המשובים נשמרים כאן לעיונכם. מידע בטיחותי שהועבר למנהל אינו מוצג מחדש במסך זה.</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{submitted.map(item=><article id={`feedback-${item.registration_id}`} key={item.id} className="scroll-mt-24 rounded-2xl border bg-white p-5"><h3 className="text-xl font-black">{item.activityTitle}</h3><p className="font-bold text-violet-800">עבור {item.childName}</p><time className="mt-1 block text-sm font-bold text-slate-500">{new Date(item.submitted_at).toLocaleDateString('he-IL')}</time><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><Summary label="מקצועיות" value={item.professionalism}/><Summary label="סבלנות" value={item.patience_listening}/><Summary label="בהירות" value={item.clarity}/><Summary label="המלצה" value={item.recommendation}/></div>{item.worked_well&&<p className="mt-3 whitespace-pre-wrap text-slate-700"><strong>מה עבד טוב: </strong>{item.worked_well}</p>}{item.could_improve&&<p className="mt-2 whitespace-pre-wrap text-slate-700"><strong>מה אפשר לשפר: </strong>{item.could_improve}</p>}</article>)}</div></section>}
 {selected&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4"><section role="dialog" aria-modal="true" className="mx-auto my-5 max-w-3xl rounded-3xl bg-white p-5 shadow-2xl sm:p-8"><div className="flex items-start justify-between"><div><h2 className="text-2xl font-black">משוב על {selected.activityTitle}</h2><p className="text-slate-600">עבור {selected.childName}</p></div><button onClick={()=>setSelected(null)} aria-label="סגירה" className="grid size-11 place-items-center rounded-full bg-slate-100 text-2xl">×</button></div>
  <Field label="האם הילד/ה השתתף/ה?"><select value={form.attendance} onChange={e=>setForm({...form,attendance:e.target.value})} className={input}><option value="attended">השתתף/ה</option><option value="partially_attended">השתתף/ה באופן חלקי</option><option value="did_not_attend">לא השתתף/ה</option><option value="activity_did_not_happen">הפעילות לא התקיימה</option></select></Field>
  <div className="mt-6 grid gap-5">{questions.map(([key,label])=><fieldset key={key} className="rounded-2xl border p-4"><legend className="px-2 font-black">{label}</legend><div className="mt-2 grid gap-2 sm:grid-cols-5">{[1,2,3,4,5].map(score=><label key={score} className={`cursor-pointer rounded-xl border p-3 text-center text-sm font-bold ${form[key]===score?'border-violet-700 bg-violet-700 text-white':'bg-white text-slate-800'}`}><input type="radio" className="sr-only" name={key} checked={form[key]===score} onChange={()=>setForm({...form,[key]:score})}/><span className="block text-lg">{score}</span>{labels[score]}</label>)}</div></fieldset>)}</div>
  <Field label="עמידה בזמנים"><select value={form.punctuality} onChange={e=>setForm({...form,punctuality:e.target.value})} className={input}><option value="on_time">הגיע/ה בזמן</option><option value="slightly_late_notified">איחר/ה מעט והודיע/ה</option><option value="late_without_notice">איחר/ה ללא הודעה</option><option value="activity_did_not_happen">הפעילות לא התקיימה</option></select></Field>
  <Field label="מה עבד טוב?"><textarea className={input+' min-h-24'} maxLength={1500} value={form.workedWell} onChange={e=>setForm({...form,workedWell:e.target.value})}/></Field><Field label="מה אפשר לשפר?"><textarea className={input+' min-h-24'} maxLength={1500} value={form.couldImprove} onChange={e=>setForm({...form,couldImprove:e.target.value})}/></Field>
  <fieldset className="mt-6 rounded-2xl border-2 border-amber-300 bg-amber-50 p-4"><legend className="px-2 font-black">בטיחות ופרטיות — למנהל בלבד</legend><Check label="היה רגע שגרם לילד/ה או לי אי־נוחות" checked={form.feltUncomfortable} onChange={value=>setForm({...form,feltUncomfortable:value})}/><Check label="התרחש אירוע בטיחותי" checked={form.safetyIncident} onChange={value=>setForm({...form,safetyIncident:value})}/><Check label="אני מבקש/ת שמנהל יחזור אליי" checked={form.requestsAdminContact} onChange={value=>setForm({...form,requestsAdminContact:value})}/><textarea placeholder="פרטים פרטיים למנהל בלבד" className={input+' mt-3 min-h-24'} maxLength={2500} value={form.privateSafetyDetails} onChange={e=>setForm({...form,privateSafetyDetails:e.target.value})}/></fieldset>
  <Check label="אני מסכים/ה שהמלצה מילולית מתאימה תישקל לפרסום לאחר בדיקת מנהל" checked={form.allowPublicQuote} onChange={value=>setForm({...form,allowPublicQuote:value})}/>
  <div className="mt-7 flex gap-3"><button onClick={submit} disabled={busy} className="rounded-xl bg-violet-700 px-6 py-3 font-black text-white disabled:opacity-50">{busy?'שומר...':'שליחת המשוב'}</button><button onClick={()=>setSelected(null)} className="rounded-xl border px-6 py-3 font-black">לא עכשיו</button></div>
 </section></div>}
 </section>
}
const input="mt-2 min-h-12 w-full rounded-xl border-2 border-slate-400 bg-white p-3 font-semibold text-slate-950 outline-none focus:border-violet-700 focus:ring-4 focus:ring-violet-100";
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mt-6 block font-black">{label}{children}</label>}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label className="mt-3 flex cursor-pointer items-start gap-3 rounded-xl bg-white p-3 font-bold"><input type="checkbox" className="mt-1 size-5 accent-violet-700" checked={checked} onChange={e=>onChange(e.target.checked)}/>{label}</label>}
function Summary({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-violet-50 p-3"><span className="font-bold text-violet-900">{label}</span><strong className="block text-lg">{value}/5</strong></div>}
