"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { createContext, useContext, useEffect, useState } from "react";
import { getDashboardPath } from "@/lib/auth-routing";
import { supabase } from "@/lib/supabase";
const navigation = [{ href: "/dashboard/parent", label: "עמוד הבית" }, { href: "/dashboard/parent/activities", label: "הפעילויות שלי" }, { href: "/dashboard/parent/requests", label: "הבקשות והפגישות שלי", badge: "requests" }, { href: "/dashboard/parent/feedback", label: "משובים להשלמה", badge: "feedback" }, { href: "/dashboard/parent/preferences", label: "הילדים והעדפות" }, { href: "/dashboard/parent/account", label: "החשבון שלי" }];
const ParentDashboardContext = createContext({ actionRequiredCount: 0 });
export function useParentDashboard() { return useContext(ParentDashboardContext); }
export default function ParentDashboardShell({ children }: { children: React.ReactNode }) {
 const pathname = usePathname(), router = useRouter(); const [ready,setReady]=useState(false), [name,setName]=useState(""), [actionRequiredCount,setActionRequiredCount]=useState(0), [feedbackCount,setFeedbackCount]=useState(0);
 useEffect(()=>{ let active=true; async function load(){ const {data}=await supabase.auth.getUser(); if(!active)return; if(!data.user){router.replace("/login");return;} const dashboardPath=await getDashboardPath(data.user.id); if(!active)return; if(dashboardPath!=="/dashboard/parent"){router.replace(dashboardPath);return;} setName(data.user.user_metadata?.first_name??""); const {data:sessionData}=await supabase.auth.getSession(); const token=sessionData.session?.access_token; if(token){const headers={Authorization:`Bearer ${token}`};const[response,feedbackResponse]=await Promise.all([fetch("/api/meeting-requests",{headers,cache:"no-store"}),fetch("/api/parent/activity-feedback",{headers,cache:"no-store"})]);if(response.ok){const body=await response.json();setActionRequiredCount((body.requests??[]).filter((request:{status?:string})=>request.status==="alternative_proposed").length);}if(feedbackResponse.ok)setFeedbackCount((await feedbackResponse.json()).pendingCount??0);} if(active)setReady(true);} void load(); return()=>{active=false;};},[router,pathname]);
 if(!ready)return <main dir="rtl" className="grid min-h-screen place-items-center bg-slate-50"><p role="status" className="font-bold text-slate-600">טוען את האזור האישי...</p></main>;
 const nav=(mobile=false)=><nav aria-label={mobile?"ניווט הורים בנייד":"ניווט הורים"} className="grid gap-1">{navigation.map(item=>{const isActive=item.href==="/dashboard/parent"?pathname===item.href:pathname.startsWith(item.href);const badge="badge" in item?item.badge:undefined;const count=badge==="requests"?actionRequiredCount:badge==="feedback"?feedbackCount:0;return <Link key={item.href} href={item.href} aria-current={isActive?"page":undefined} className={`flex min-h-12 items-center justify-between gap-3 rounded-xl px-4 py-3 font-bold transition focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 ${isActive?"bg-blue-700 text-white":"text-slate-700 hover:bg-blue-50 hover:text-blue-800"}`}><span>{item.label}</span>{count>0&&<span aria-label={`${count} פריטים ממתינים`} className={`rounded-full px-2 py-0.5 text-xs font-black ${isActive?"bg-white text-violet-800":"bg-violet-200 text-violet-900"}`}>{count}</span>}</Link>;})}</nav>;
 return <ParentDashboardContext.Provider value={{actionRequiredCount}}><div dir="rtl" className="min-h-screen bg-slate-50 text-slate-950"><header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[96rem] items-center justify-between gap-4 px-4 py-3 sm:px-6"><Link href="/dashboard/parent" aria-label="MentorLink – עמוד הבית להורים" className="flex items-center gap-3 font-black text-blue-700"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-violet-600 text-xl text-white">M</span><span className="text-xl">MentorLink</span></Link><div className="flex items-center gap-3"><span className="hidden font-bold text-slate-700 sm:inline">{name?`שלום, ${name}`:"האזור האישי"}</span><button type="button" onClick={async()=>{await supabase.auth.signOut();router.push("/login");}} className="min-h-11 rounded-xl border border-slate-300 px-4 py-2 font-bold hover:bg-slate-100">התנתקות</button><details className="relative lg:hidden"><summary className="cursor-pointer list-none rounded-xl border border-slate-300 px-4 py-2.5 font-black marker:content-none">תפריט</summary><div className="absolute left-0 top-14 w-[min(20rem,calc(100vw-2rem))] rounded-2xl border border-slate-200 bg-white p-3 shadow-2xl">{nav(true)}</div></details></div></div></header><div className="mx-auto grid max-w-[96rem] lg:grid-cols-[18rem_minmax(0,1fr)]"><aside className="sticky top-[69px] hidden h-[calc(100vh-69px)] border-l border-slate-200 bg-white p-5 lg:block"><p className="mb-4 px-4 text-sm font-black text-slate-500">האזור האישי להורים</p>{nav()}</aside><main className="min-w-0 px-4 py-8 sm:px-6 lg:px-10">{children}</main></div></div></ParentDashboardContext.Provider>;
}
