"use client";
import Link from "next/link";
import { useMentorDashboard } from "./_components/MentorDashboardShell";

export default function MentorDashboardPage(){
 const summary=useMentorDashboard();
 const cards=[
  {title:"בקשות פגישה שמחכות לפעולתך",value:summary.mentorActionMeetings,href:"/dashboard/mentor/meetings?view=mentor-action",important:summary.mentorActionMeetings>0},
  {title:"הצעות שמחכות לתשובת ההורה",value:summary.waitingForParent,href:"/dashboard/mentor/meetings?view=waiting-parent"},
  {title:"פניות כלליות פעילות",value:summary.activeInquiries,href:"/dashboard/mentor/inquiries#active-inquiries",important:summary.activeInquiries>0},
  {title:"פגישות קרובות שאושרו",value:summary.upcomingMeetings,href:"/dashboard/mentor/meetings?view=upcoming-approved"},
 ];
 const state=(value:boolean|null,positive:string,negative:string)=>value===null?"לא ניתן לטעון כעת":value?positive:negative;
 if(summary.summaryState==="loading")return <p role="status" className="rounded-2xl bg-white p-6 font-bold text-slate-600">טוען את סיכום הפעילות...</p>;
 if(summary.summaryState==="error")return <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-6 text-red-800"><h1 className="text-2xl font-black">לא ניתן לטעון את סיכום הפעילות כרגע</h1><p className="mt-2">אפשר לנסות לרענן את העמוד או לעבור ישירות דרך תפריט החונכים.</p></div>;
 return <div className="mx-auto max-w-6xl"><p className="font-black text-blue-700">האזור האישי לחונכים</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">עמוד הבית</h1><p className="mt-3 text-slate-600">כל מה שדורש את תשומת לבכם, במקום אחד.</p>
  <section aria-labelledby="mentor-activities-title" className="mt-8 rounded-3xl bg-gradient-to-l from-violet-700 via-blue-700 to-cyan-600 p-6 text-white shadow-lg"><p className="font-bold text-cyan-100">דרך חדשה לפגוש משפחות</p><h2 id="mentor-activities-title" className="mt-1 text-2xl font-black sm:text-3xl">הפעילויות שלך במרכז</h2><p className="mt-2 max-w-2xl text-blue-50">פתחו פעילות חד־פעמית או סדרה, ונהלו את הטיוטות וההרשמות מאזור אחד.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/dashboard/mentor/activities/new" className="min-h-12 rounded-xl bg-white px-5 py-3 font-black text-blue-800 shadow-md transition hover:bg-blue-50 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white">פתיחת פעילות חדשה</Link><Link href="/dashboard/mentor/activities" className="min-h-12 rounded-xl border border-white/70 bg-blue-950/20 px-5 py-3 font-black text-white transition hover:bg-blue-950/35 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-white">הפעילויות שלי</Link></div></section>  <section aria-labelledby="mentor-actions-title" className="mt-8"><h2 id="mentor-actions-title" className="text-2xl font-black">מה דורש טיפול</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{cards.map((card)=><Link key={card.title} href={card.href} className={`rounded-2xl border bg-white p-5 shadow-sm transition hover:border-blue-300 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 ${card.important?"border-amber-300 ring-2 ring-amber-100":"border-slate-200"}`}><span className="text-3xl font-black text-blue-700">{card.value}</span><h3 className="mt-2 font-black">{card.title}</h3><span className="mt-3 inline-block text-sm font-bold text-blue-700">לצפייה ←</span></Link>)}</div></section>
  <section aria-labelledby="mentor-status-title" className="mt-8"><h2 id="mentor-status-title" className="text-2xl font-black">מצב החשבון</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Link href="/dashboard/mentor/scheduling" className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-black">מצב הזמינות</h3><p className="mt-2 text-slate-600">{state(summary.availabilityConfigured,"קיימת זמינות פעילה","עדיין לא הוגדרה זמינות פעילה")}</p></Link><Link href="/dashboard/mentor/profile" className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-black">מצב הפרופיל</h3><p className="mt-2 text-slate-600">{state(summary.profileConfigured,"פרטי הפרופיל הבסיסיים הושלמו","הפרופיל עדיין דורש השלמה")}</p></Link></div></section>
  <section aria-labelledby="mentor-quick-title" className="mt-8"><h2 id="mentor-quick-title" className="text-2xl font-black">פעולות מהירות</h2><div className="mt-4 flex flex-wrap gap-3"><Link href="/dashboard/mentor/activities/new" className="min-h-12 rounded-xl bg-blue-700 px-5 py-3 font-black text-white">פתיחת פעילות חדשה</Link><Link href="/dashboard/mentor/discover" className="min-h-12 rounded-xl border border-blue-300 bg-white px-5 py-3 font-black text-blue-800">חיפוש חונכים ופעילויות</Link></div></section>
 </div>
}
