"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Registration = { id: string; child_first_name: string; status: string; activity: { title: string; status: string; venue_name: string | null; location_type: string } | null; sessions: { starts_at: string; ends_at: string }[] };
const status: Record<string, { label: string; style: string }> = { registered: { label: "רשום/ה", style: "bg-green-100 text-green-800" }, waitlisted: { label: "רשימת המתנה", style: "bg-amber-100 text-amber-900" }, cancelled: { label: "בוטלה", style: "bg-red-100 text-red-800" } };
export default function ParentRegistrations() {
 const [rows,setRows]=useState<Registration[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState("");
 async function load(){setLoading(true);const token=(await supabase.auth.getSession()).data.session?.access_token;const response=await fetch("/api/parent/activity-registrations",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(response.ok)setRows((await response.json()).registrations??[]);else setMessage("לא ניתן לטעון את ההרשמות כרגע.");setLoading(false);}
 useEffect(()=>{void load();},[]);
 async function cancel(id:string){if(!confirm("לבטל את ההרשמה של הילד/ה לפעילות?"))return;const token=(await supabase.auth.getSession()).data.session?.access_token;const response=await fetch(`/api/parent/activity-registrations?registrationId=${id}`,{method:"DELETE",headers:{Authorization:`Bearer ${token}`}});setMessage(response.ok?"ההרשמה בוטלה.":"לא ניתן לבטל את ההרשמה.");if(response.ok)await load();}
 if(loading)return <p className="mt-8 rounded-2xl bg-white p-6 font-bold">טוען הרשמות...</p>;
 return <div className="mt-8">{message&&<p role="status" className="mb-4 rounded-xl bg-blue-50 p-4 font-bold text-blue-900">{message}</p>}{rows.length?<div className="grid gap-5 md:grid-cols-2">{rows.map((row)=>{const next=row.sessions.find((session)=>new Date(session.starts_at)>new Date());const badge=status[row.status]??status.cancelled;return <article key={row.id} className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-violet-700">עבור {row.child_first_name}</p><h2 className="mt-1 text-2xl font-black">{row.activity?.title??"פעילות"}</h2></div><span className={`rounded-full px-3 py-1 text-sm font-black ${badge.style}`}>{badge.label}</span></div>{next&&<div className="mt-5 rounded-2xl bg-blue-700 p-4 text-white"><p className="font-black">המפגש הקרוב</p><p>{new Intl.DateTimeFormat("he-IL",{weekday:"long",day:"numeric",month:"long",hour:"2-digit",minute:"2-digit"}).format(new Date(next.starts_at))}</p></div>}{row.status!=="cancelled"&&<button onClick={()=>cancel(row.id)} className="mt-5 rounded-xl border border-red-300 px-4 py-2 font-bold text-red-700">ביטול הרשמה לילד/ה</button>}</article>})}</div>:<div className="rounded-3xl border border-dashed bg-white p-10 text-center"><h2 className="text-xl font-black">עדיין אין הרשמות לפעילויות</h2><p className="mt-2 text-slate-600">הפעילויות שתבחרו יופיעו כאן לפי הילדים.</p></div>}</div>;
}
